### ISSUE TITLE
配置Local REST API 插件的步骤少了一步

### ISSUE THREAD

**Issue by joyong** [slarkvan/syncwise#1]
如果Local REST API 配置中开启“enable encrypted(https) server”选项的话，需要按照插件说明中下载证书并安装，不然在chrome插件检查连接的时候会报错：Obsidian Connect Failed! Failed to fetch
或者简单的办法就是不开启“enable encrypted(https) server”选项

**Comment by slarkvan** [comment]
好的，我今天更新下帮助文档
