### ISSUE TITLE
点击开始收集没有反应

### ISSUE THREAD

**Issue by y4code** [slarkvan/syncwise#4]
始终显示“已收集0条书签”，页面也不会滚动，即使已手动点开 bookmark 页面

尝试过[这里](https://github.com/slarkvan/syncwise/issues/2#issuecomment-2074609482 )提到的方法，但仍然不管用

普通浏览模式，Console 中显示如下
``` console
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
bookmarks:1 The resource https://abs.twimg.com/responsive-web/client-web/Chirp-Regular.80fda27a.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
在无痕模式中尝试，没有任何 error or warning

- Check Connection 没有问题：Logseq Connect Succeed!
- Google Chrome 版本 126.0.6478.127（正式版本） (arm64)

<img width="609" alt="image" src="https://github.com/user-attachments/assets/3f782b24-aacf-4ab4-b270-87e49893da3b">
<img width="1698" alt="image" src="https://github.com/user-attachments/assets/b0d3c5a4-cc14-482c-9da3-776c3ddea77d">

**Comment by slarkvan** [comment]
你好，你截图里的报红是 Twitter 自己的。和插件没关系。
你可以试试在`控制台` 的 `应用` 的 `本地存储`里，先清空，然后刷新页面。重新操作试试看

**Comment by y4code** [comment]
谢谢，仍然不行，我放弃了，祝好。

**Comment by y4code** [comment]
谢谢，仍然不行，我放弃了，祝好。
